apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
  name: otel-svc-monitor
  namespace: mock-ns
spec:
  endpoints:
  - interval: 30s
    port: prometheus
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
